/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;
import EDD.*;
import java.awt.BorderLayout;
import javaapplication7.Documento;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Gustavo
 */
public class Vista extends javax.swing.JPanel {
    Heap heap;
    String registro;
    Ventana_Principal origen;
    /**
     * Creates new form Vista_Arbol
     */
    public Vista() {
        initComponents();
        
    }
    
    public Vista(Heap heap, String registro, Ventana_Principal origen) {
        this.heap = heap;
        this.registro = registro;
        this.origen = origen;
        initComponents();
        initArbol(heap);
        initTextRegistro(registro);
        
//        initArbol();
//        MonticuloBinario mb = new MonticuloBinario();
//        PlanoArbol.setUI(mb);
        
    }

    public void initTextRegistro(String registros){
        jTextArea1.setText(registros);
    }
    
    public void initArbol(Heap heap){
        ShowArbol(heap);
        
    }
    
    private void ShowArbol(Heap heap){
        JPanel n = new MonticuloBinario(heap);
        n.setLocation(0,0);
        n.setSize(400,400);
        PlanoArbol.removeAll();
        PlanoArbol.add(n, BorderLayout.CENTER);
        PlanoArbol.revalidate();
        PlanoArbol.repaint();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ScrollRegistro = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        PlanoArbol = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(204, 206, 222));

        jButton1.setText("Liberar impresora");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar de la cola");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        ScrollRegistro.setViewportView(jTextArea1);

        javax.swing.GroupLayout PlanoArbolLayout = new javax.swing.GroupLayout(PlanoArbol);
        PlanoArbol.setLayout(PlanoArbolLayout);
        PlanoArbolLayout.setHorizontalGroup(
            PlanoArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );
        PlanoArbolLayout.setVerticalGroup(
            PlanoArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PlanoArbol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(ScrollRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollRegistro)
                    .addComponent(PlanoArbol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here: Eliminar de la cola
        String s = JOptionPane.showInputDialog(null, "Ingrese el nombre del documento");
        heap.Eliminar(s);
        registro = "Se ha eliminado " + s + " de la cola\n";
        origen.registro += registro;
        this.initTextRegistro(origen.registro);
        
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        Documento s = heap.getRoot();
        heap.ReordenarArriba();
        registro = "Se imprimió " + s.getNombre() + s.getTipo()  + "\n";
        origen.registro += registro;
        this.initTextRegistro(origen.registro);
        
    }                                           


    // Variables declaration - do not modify                     
    private javax.swing.JPanel PlanoArbol;
    private javax.swing.JScrollPane ScrollRegistro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration                   
}
